GET be-2-medan-20-production.up.railway.app/product

###
POST  be-2-medan-20-production.up.railway.app/product
Content-Type: application/json
{
    "name": "Pad Thai",
    "price": 30.99,
    "product_picture": "/sayur2.png"
}

###
POST http://localhost:5000/add-to-order
Content-Type: application/json

{
        "productId": 1,
        "name": "Bionico Fruit salad",
        "price": 19.99,
        "quantity": 2
}

###
GET http://localhost:5000/view-order/1

###
POST http://localhost:5000/place-order
Content-Type: application/json

{
        "orderId": 1,
        "name": "Jhon",
        "phone": "123456789",
        "address": "Jl. Merdeka"
    }


###
GET http://localhost:5000/view-order-detail/1